100QA/QA_100/QA_100/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from QA import views as general_view
urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', general_view.home, name='home')
    #path ('signup/',accounts_views.signup, name ='signup')
]

100QA/QA_100/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view
from account import views

app_name='account'
urlpatterns = [
    path('signup/', views.signup, name = 'signup'),
    path('logout/', auth_view.LogoutView.as_view(), name='logout'),
    path('login/', auth_view.LoginView.as_view
     (template_name='account/login.html'), name = 'login'),
    path ('profile/<username>', views.save_profile, name = 'profile'),
]

100QA/QA_100/QA/models.py
from django.db import models

# Create your models here.

100QA/QA_100/account/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class CustomQuestion(models.Model):
    question = models.TextField(max_length=1000, blank = True)
    profile = models.ForeignKey('Profile', null=True, blank=True,
                                on_delete=models.CASCADE, related_name='custom')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    location = models.CharField(max_length=30, blank=True)
    birth_date = models.DateField(null=True, blank=True)
    partner = models.URLField(null=True, blank=True)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

100QA/QA_100/account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core import validators
from django.forms import modelformset_factory

from . models import Profile, CustomQuestion

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)
    botcatcher = forms.CharField(
        required=False, widget=forms.HiddenInput,
        validators=[validators.MaxLengthValidator(0)]
    )
    class Meta:
        model = User
        fields = ('username','email','password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in ['username', 'email','password1','password2']:
            self.fields[field].help_text = None
            self.fields[field].widget.attrs['placeholder'] = self.fields[field].label


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ('user',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].help_text = None
            #placeholder for each field to update only changed field. otherwise this has to go through
            #overriding save method which is tedious since user can't submit an empty/null value
            if hasattr(kwargs['instance'], field):
                if getattr(kwargs['instance'], field) == None or getattr(kwargs['instance'], field) =='':
                    self.fields[field].widget.attrs['placeholder'] = field
                else:
                    self.fields[field].widget.attrs['placeholder'] = getattr(kwargs['instance'], field)

CustomQuestionFormset = modelformset_factory(
    CustomQuestion,
    fields=('question', ),
    extra=1,
    widgets={
        'question': forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Enter Your Question Here'
            }
        )
    }
)

100QA/QA_100/QA/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    return render(request, 'QA/home.html')

100QA/QA_100/account/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import login as auth_login
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


from .forms import SignUpForm, UpdateProfileForm, CustomQuestionFormset
from .models import CustomQuestion
# Create your views here.

def signup(request):
    form = SignUpForm

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return render(request, 'QA/home.html')

    return render(request, 'account/signup.html', {"form": form})

@login_required(login_url='/account/login/')
def save_profile(request, username):
    current_user = get_object_or_404(User, username=username)
    form = UpdateProfileForm(instance = current_user.profile)
    formset = CustomQuestionFormset(queryset=CustomQuestion.objects.none())
    #could be simply done by user.username, but mehhh
    if (request.user.id == current_user.id):
        if request.method == 'POST':
            form = UpdateProfileForm(request.POST, instance=current_user.profile)
            formset = CustomQuestionFormset(request.POST)
            if form.is_valid() and formset.is_valid:
                profile = form.save()
                for custom in formset:
                    cq = custom.save(commit=False)
                    cq.profile = profile
                    cq.save()

                #TODO: gotta fix this redirection later.
                return HttpResponseRedirect(request.path_info)
        return render(request, 'account/profile.html', {"form": form, "formset": formset})
    #TODO:Maybe if a user try to access someone's profile that has nothing to with that person
    #more than 3 times,delete that account?
    return render(request, 'redirection.html', {'message': "Dont even try!"})

100QA/QA_100/templates/QA/home.html
{% extends 'base.html' %}
{% load staticfiles%}
{% block title%} Welcome to 100QA {% endblock %}
{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'css/QA/home.css' %}"/>
{% endblock %}
{% block content %}
  <div class="first-box" >
    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
      Lorem ipsum dolor sit amet, consectetur adipisicing elit,
      sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
      nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in
      reprehenderit in voluptate velit esse cillum dolore eu fugiat
      nulla pariatur. Excepteur sint occaecat cupidatat non proident,
      sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>
  <div class="second-box">
    {% if not user.is_authenticated %}
    <span>
      <a href="{%url 'account:login'%}">Log in</a>
    </span>
    <span>
      <a href="{%url 'account:signup'%}">No account?</a>

    </span>
    {% endif %}

  </div>

{% endblock %}

100QA/QA_100/templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}QA100{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}"/>
    <script src="{% static 'js/base.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
    {% block stylesheet %} {% endblock %}
  </head>
  <body>
    <ul class = "navbar">
      {% if user.is_authenticated %}
        <li class = "first">{{user.username}} .</li>

        <li>
          <a href="{% url 'account:logout'%}">LOGOUT</a>
        </li>
        <li>
          <a href="{% url 'account:profile' user.username %}">PROFILE</a>
        </li>
      {% else %}
        <li>
          <a href="{% url 'account:login'%}">LOGIN</a>
        </li>
      {% endif %}
      <li>
        <a href="{% url 'home' %}">HOME</a>
      </li>
    </ul>

    <div class = "for_padding">
      {% block content %}
      {% endblock %}
    </div>

  </body>
</html>

100QA/QA_100/templates/form.html
{% for field in form%}
<p>
  {{field.widget}}
  {{field}}
</p>
  {% if form.is_bound %}
    {% if field.errors %}
      {% for error in field.errors %}
        {{error}}
      {% endfor %}
    {% endif %}
  {% endif %}
    {% if field.help_text %}
    <!-- Removed django form help text, but leaving just in case for later use. -->
      <small class="form-text text-muted">
      {{ field.help_text }}
      </small>
    {% endif %}
{% endfor %}

100QA/QA_100/templates/redirection.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Redirecting..</title>
  </head>
  <body>
    <p>{{message}} </p>
    <script>
      function redirect(){
         window.location.href = "{% url 'home'%}";
      }

      setTimeout(redirect, 2000); //2000 is equivalent to 2 seconds
    </script>
  </body>
</html>